export default {
    "whatIs": "Cursor is an AI-powered code editor designed for pair-programming with a powerful AI. It's built from the ground up to help developers write, understand, and refactor code faster and more efficiently. It's a fork of VS Code, so it supports all its extensions.",
    "useCases": [
        "<strong>AI-Assisted Coding:</strong> Get code suggestions, completions, and entire functions generated by the AI.",
        "<strong>Code Understanding:</strong> Ask questions about a codebase to understand its functionality.",
        "<strong>Refactoring:</strong> Refactor large chunks of code with a single prompt.",
        "<strong>Debugging:</strong> Get help from the AI to find and fix bugs."
    ],
    "gettingStarted": [
        "<strong>Download and Install:</strong> Download and install the Cursor editor from the official website.",
        "<strong>Open a Project:</strong> Open a folder or project you want to work on.",
        "<strong>Use the AI:</strong> Use the built-in AI features like \"Chat\" or \"Edit\" to interact with the AI.",
        "<strong>Prompt the AI:</strong> Write prompts to ask the AI to generate, refactor, or explain code."
    ],
    "tips": [
        "<strong>Be Specific:</strong> Provide clear and specific instructions to the AI.",
        "<strong>Provide Context:</strong> When asking for changes, select the relevant code block to provide context.",
        "<strong>Iterate:</strong> If the first result is not perfect, iterate and refine your prompts.",
        "<strong>Use for Learning:</strong> Ask the AI to explain complex code snippets to learn new things."
    ]
};